# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_XayDungCSDL.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_XayDungCSDL(object):
    def setupUi(self, Dialog_XayDungCSDL):
        Dialog_XayDungCSDL.setObjectName("Dialog_XayDungCSDL")
        Dialog_XayDungCSDL.resize(400, 202)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_XayDungCSDL)
        self.buttonBox.setGeometry(QtCore.QRect(40, 140, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_XayDungCSDL)
        self.label.setGeometry(QtCore.QRect(20, 50, 191, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_XayDungCSDL)
        self.lineEdit.setGeometry(QtCore.QRect(20, 70, 321, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.InButton = QtWidgets.QPushButton(Dialog_XayDungCSDL)
        self.InButton.setGeometry(QtCore.QRect(350, 70, 31, 24))
        self.InButton.setObjectName("InButton")

        self.retranslateUi(Dialog_XayDungCSDL)
        self.buttonBox.accepted.connect(Dialog_XayDungCSDL.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_XayDungCSDL.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_XayDungCSDL)

    def retranslateUi(self, Dialog_XayDungCSDL):
        _translate = QtCore.QCoreApplication.translate
        Dialog_XayDungCSDL.setWindowTitle(_translate("Dialog_XayDungCSDL", "v5PFES - Xây dựng cơ sở dữ liệu"))
        self.label.setText(_translate("Dialog_XayDungCSDL", "Chọn lớp bản đồ đầu vào (.shp)"))
        self.InButton.setText(_translate("Dialog_XayDungCSDL", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_XayDungCSDL = QtWidgets.QDialog()
    ui = Ui_Dialog_XayDungCSDL()
    ui.setupUi(Dialog_XayDungCSDL)
    Dialog_XayDungCSDL.show()
    sys.exit(app.exec_())
