# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_CapNhatNSK.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CapNhatNSK(object):
    def setupUi(self, Dialog_CapNhatNSK):
        Dialog_CapNhatNSK.setObjectName("Dialog_CapNhatNSK")
        Dialog_CapNhatNSK.resize(521, 312)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_CapNhatNSK)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_CapNhatNSK)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog_CapNhatNSK)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 391, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_CapNhatNSK)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 161, 16))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Dialog_CapNhatNSK)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 461, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Inpath = QtWidgets.QLineEdit(self.layoutWidget)
        self.Inpath.setObjectName("Inpath")
        self.gridLayout.addWidget(self.Inpath, 0, 0, 1, 1)
        self.btn_Inp = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_Inp.setObjectName("btn_Inp")
        self.gridLayout.addWidget(self.btn_Inp, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_CapNhatNSK)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 120, 461, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.unPayment = QtWidgets.QLineEdit(self.layoutWidget1)
        self.unPayment.setObjectName("unPayment")
        self.gridLayout_2.addWidget(self.unPayment, 0, 0, 1, 1)
        self.btn_nsk = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_nsk.setObjectName("btn_nsk")
        self.gridLayout_2.addWidget(self.btn_nsk, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_CapNhatNSK)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 190, 461, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Outpath = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Outpath.setObjectName("Outpath")
        self.gridLayout_3.addWidget(self.Outpath, 0, 0, 1, 1)
        self.btnOut = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnOut.setObjectName("btnOut")
        self.gridLayout_3.addWidget(self.btnOut, 0, 1, 1, 1)

        self.retranslateUi(Dialog_CapNhatNSK)
        self.buttonBox.accepted.connect(Dialog_CapNhatNSK.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_CapNhatNSK.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_CapNhatNSK)

    def retranslateUi(self, Dialog_CapNhatNSK):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CapNhatNSK.setWindowTitle(_translate("Dialog_CapNhatNSK", "v5PFES - Cập nhật khu vực đã có nguồn đầu tư khác"))
        self.label.setText(_translate("Dialog_CapNhatNSK", "Chọn lớp bản đồ đầu vào (.shp)"))
        self.label_3.setText(_translate("Dialog_CapNhatNSK", "Chọn lớp ranh giới khu vực đã có đầu tư từ nguồn ngân sách khác (.shp)"))
        self.label_4.setText(_translate("Dialog_CapNhatNSK", "Chọn lớp bản đồ đầu ra  (.shp)"))
        self.btn_Inp.setText(_translate("Dialog_CapNhatNSK", "..."))
        self.btn_nsk.setText(_translate("Dialog_CapNhatNSK", "..."))
        self.btnOut.setText(_translate("Dialog_CapNhatNSK", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_CapNhatNSK = QtWidgets.QDialog()
    ui = Ui_Dialog_CapNhatNSK()
    ui.setupUi(Dialog_CapNhatNSK)
    Dialog_CapNhatNSK.show()
    sys.exit(app.exec_())
