# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_CapNhatDG.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CapNhatDG(object):
    def setupUi(self, Dialog_CapNhatDG):
        Dialog_CapNhatDG.setObjectName("Dialog_CapNhatDG")
        Dialog_CapNhatDG.resize(521, 376)
        self.label1 = QtWidgets.QLabel(Dialog_CapNhatDG)
        self.label1.setGeometry(QtCore.QRect(30, 30, 171, 16))
        self.label1.setObjectName("label1")
        self.label_2 = QtWidgets.QLabel(Dialog_CapNhatDG)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_CapNhatDG)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 181, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Dialog_CapNhatDG)
        self.comboBox.setGeometry(QtCore.QRect(30, 120, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_CapNhatDG)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 461, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.inputShapefile = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputShapefile.setObjectName("inputShapefile")
        self.gridLayout.addWidget(self.inputShapefile, 0, 0, 1, 1)
        self.btnInputShp = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInputShp.setObjectName("btnInputShp")
        self.gridLayout.addWidget(self.btnInputShp, 0, 1, 1, 1)
        self.btnPrice = QtWidgets.QPushButton(Dialog_CapNhatDG)
        self.btnPrice.setGeometry(QtCore.QRect(409, 120, 81, 24))
        self.btnPrice.setObjectName("btnPrice")
        self.spBx_Price = QtWidgets.QSpinBox(Dialog_CapNhatDG)
        self.spBx_Price.setGeometry(QtCore.QRect(30, 190, 301, 22))
        self.spBx_Price.setObjectName("spBx_Price")
        self.label_4 = QtWidgets.QLabel(Dialog_CapNhatDG)
        self.label_4.setGeometry(QtCore.QRect(250, 100, 161, 15))
        self.label_4.setObjectName("label_4")
        self.InMoney = QtWidgets.QLineEdit(Dialog_CapNhatDG)
        self.InMoney.setGeometry(QtCore.QRect(250, 120, 151, 22))
        self.InMoney.setObjectName("InMoney")
        self.btnUpdate = QtWidgets.QPushButton(Dialog_CapNhatDG)
        self.btnUpdate.setGeometry(QtCore.QRect(339, 190, 151, 24))
        self.btnUpdate.setObjectName("btnUpdate")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog_CapNhatDG)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 230, 461, 79))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 291, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dg_cBx = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.dg_cBx.setObjectName("dg_cBx")
        self.verticalLayout_5.addWidget(self.dg_cBx)
        self.xdmct_cBx = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.xdmct_cBx.setObjectName("xdmct_cBx")
        self.verticalLayout_5.addWidget(self.xdmct_cBx)
        self.buttonBox = QtWidgets.QPushButton(Dialog_CapNhatDG)
        self.buttonBox.setGeometry(QtCore.QRect(340, 330, 75, 24))
        self.buttonBox.setObjectName("buttonBox")
        self.btnCancel = QtWidgets.QPushButton(Dialog_CapNhatDG)
        self.btnCancel.setGeometry(QtCore.QRect(417, 330, 75, 24))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Dialog_CapNhatDG)
        QtCore.QMetaObject.connectSlotsByName(Dialog_CapNhatDG)

    def retranslateUi(self, Dialog_CapNhatDG):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CapNhatDG.setWindowTitle(_translate("Dialog_CapNhatDG", "v5PFES - Cập nhật đơn giá"))
        self.label1.setText(_translate("Dialog_CapNhatDG", "Chọn lớp bản đồ đầu vào (.shp)"))
        self.label_2.setText(_translate("Dialog_CapNhatDG", "Chọn lưu vực "))
        self.label_3.setText(_translate("Dialog_CapNhatDG", "Đơn giá (VNĐ):"))
        self.btnInputShp.setText(_translate("Dialog_CapNhatDG", "..."))
        self.btnPrice.setText(_translate("Dialog_CapNhatDG", "Tính đơn giá"))
        self.label_4.setText(_translate("Dialog_CapNhatDG", "Nhập tổng số tiền (VNĐ):"))
        self.btnUpdate.setText(_translate("Dialog_CapNhatDG", "Cập nhật đơn giá lưu vực"))
        self.groupBox_6.setTitle(_translate("Dialog_CapNhatDG", "Xác định mức chi trả"))
        self.dg_cBx.setText(_translate("Dialog_CapNhatDG", "Tính tổng đơn giá chi trả"))
        self.xdmct_cBx.setText(_translate("Dialog_CapNhatDG", "Xác định mức chi trả"))
        self.buttonBox.setText(_translate("Dialog_CapNhatDG", "OK"))
        self.btnCancel.setText(_translate("Dialog_CapNhatDG", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_CapNhatDG = QtWidgets.QDialog()
    ui = Ui_Dialog_CapNhatDG()
    ui.setupUi(Dialog_CapNhatDG)
    Dialog_CapNhatDG.show()
    sys.exit(app.exec_())
