# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_CapNhatVCT.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CapNhatVCT(object):
    def setupUi(self, Dialog_CapNhatVCT):
        Dialog_CapNhatVCT.setObjectName("Dialog_CapNhatVCT")
        Dialog_CapNhatVCT.resize(521, 343)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_CapNhatVCT)
        self.buttonBox.setGeometry(QtCore.QRect(150, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_CapNhatVCT)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_CapNhatVCT)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_CapNhatVCT)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 181, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_CapNhatVCT)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 161, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Dialog_CapNhatVCT)
        self.comboBox.setGeometry(QtCore.QRect(30, 110, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_CapNhatVCT)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 461, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_CapNhatVCT)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 170, 461, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_CapNhatVCT)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 230, 461, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Dialog_CapNhatVCT)
        self.checkBox.setGeometry(QtCore.QRect(260, 100, 21, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_5 = QtWidgets.QLabel(Dialog_CapNhatVCT)
        self.label_5.setGeometry(QtCore.QRect(280, 100, 221, 31))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog_CapNhatVCT)
        self.buttonBox.accepted.connect(Dialog_CapNhatVCT.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_CapNhatVCT.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_CapNhatVCT)

    def retranslateUi(self, Dialog_CapNhatVCT):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CapNhatVCT.setWindowTitle(_translate("Dialog_CapNhatVCT", "v5PFES - Cập nhật vùng chi trả"))
        self.label.setText(_translate("Dialog_CapNhatVCT", "Chọn lớp bản đồ đầu vào (.shp)"))
        self.label_2.setText(_translate("Dialog_CapNhatVCT", "Chọn lưu vực "))
        self.label_3.setText(_translate("Dialog_CapNhatVCT", "Chọn lớp ranh giới lưu vực (.shp)"))
        self.label_4.setText(_translate("Dialog_CapNhatVCT", "Chọn lớp bản đồ đầu ra  (.shp)"))
        self.pushButton.setText(_translate("Dialog_CapNhatVCT", "..."))
        self.pushButton_2.setText(_translate("Dialog_CapNhatVCT", "..."))
        self.pushButton_3.setText(_translate("Dialog_CapNhatVCT", "..."))
        self.label_5.setText(_translate("Dialog_CapNhatVCT", "Bảo toàn diện tích bình sai\n"
"(Bỏ chọn để tính lại diện tích bằng máy) "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_CapNhatVCT = QtWidgets.QDialog()
    ui = Ui_Dialog_CapNhatVCT()
    ui.setupUi(Dialog_CapNhatVCT)
    Dialog_CapNhatVCT.show()
    sys.exit(app.exec_())
