# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_XuatBieuNhom1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_XuatBieuNhom1(object):
    def setupUi(self, Dialog_XuatBieuNhom1):
        Dialog_XuatBieuNhom1.setObjectName("Dialog_XuatBieuNhom1")
        Dialog_XuatBieuNhom1.resize(564, 311)
        self.com_tinh = QtWidgets.QComboBox(Dialog_XuatBieuNhom1)
        self.com_tinh.setGeometry(QtCore.QRect(20, 50, 161, 22))
        self.com_tinh.setObjectName("com_tinh")
        self.com_huyen = QtWidgets.QComboBox(Dialog_XuatBieuNhom1)
        self.com_huyen.setGeometry(QtCore.QRect(200, 50, 161, 22))
        self.com_huyen.setObjectName("com_huyen")
        self.combo_xa = QtWidgets.QComboBox(Dialog_XuatBieuNhom1)
        self.combo_xa.setGeometry(QtCore.QRect(380, 50, 161, 22))
        self.combo_xa.setObjectName("combo_xa")
        self.label = QtWidgets.QLabel(Dialog_XuatBieuNhom1)
        self.label.setGeometry(QtCore.QRect(20, 31, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_XuatBieuNhom1)
        self.label_2.setGeometry(QtCore.QRect(200, 31, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_XuatBieuNhom1)
        self.label_3.setGeometry(QtCore.QRect(383, 32, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog_XuatBieuNhom1)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 161, 16))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Dialog_XuatBieuNhom1)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 200, 521, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.output_path.setObjectName("output_path")
        self.horizontalLayout.addWidget(self.output_path)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_XuatBieuNhom1)
        self.layoutWidget1.setGeometry(QtCore.QRect(377, 250, 161, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_OK = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_OK.setObjectName("btn_OK")
        self.horizontalLayout_2.addWidget(self.btn_OK)
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.combo_thonban = QtWidgets.QComboBox(Dialog_XuatBieuNhom1)
        self.combo_thonban.setGeometry(QtCore.QRect(380, 100, 161, 22))
        self.combo_thonban.setObjectName("combo_thonban")
        self.label_4 = QtWidgets.QLabel(Dialog_XuatBieuNhom1)
        self.label_4.setGeometry(QtCore.QRect(380, 80, 161, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog_XuatBieuNhom1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_XuatBieuNhom1)

    def retranslateUi(self, Dialog_XuatBieuNhom1):
        _translate = QtCore.QCoreApplication.translate
        Dialog_XuatBieuNhom1.setWindowTitle(_translate("Dialog_XuatBieuNhom1", "v5PFES - Xuất biểu nhóm 1"))
        self.label.setText(_translate("Dialog_XuatBieuNhom1", "Chọn tỉnh"))
        self.label_2.setText(_translate("Dialog_XuatBieuNhom1", "Chọn huyện"))
        self.label_3.setText(_translate("Dialog_XuatBieuNhom1", "Chọn xã"))
        self.label_5.setText(_translate("Dialog_XuatBieuNhom1", "Chọn thư mục lưu kết quả"))
        self.toolButton.setText(_translate("Dialog_XuatBieuNhom1", "..."))
        self.btn_OK.setText(_translate("Dialog_XuatBieuNhom1", "OK"))
        self.btn_cancel.setText(_translate("Dialog_XuatBieuNhom1", "Cancel"))
        self.label_4.setText(_translate("Dialog_XuatBieuNhom1", "Chọn thôn bản"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_XuatBieuNhom1 = QtWidgets.QDialog()
    ui = Ui_Dialog_XuatBieuNhom1()
    ui.setupUi(Dialog_XuatBieuNhom1)
    Dialog_XuatBieuNhom1.show()
    sys.exit(app.exec_())
