# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\v5pfes_plugin\Dlg_ChuanHoaDBR.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_ChuanHoa(object):
    def setupUi(self, Dialog_ChuanHoa):
        Dialog_ChuanHoa.setObjectName("Dialog_ChuanHoa")
        Dialog_ChuanHoa.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_ChuanHoa.resize(411, 282)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/ifee.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_ChuanHoa.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_ChuanHoa)
        self.buttonBox.setGeometry(QtCore.QRect(60, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label1 = QtWidgets.QLabel(Dialog_ChuanHoa)
        self.label1.setGeometry(QtCore.QRect(20, 30, 361, 16))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Dialog_ChuanHoa)
        self.label2.setGeometry(QtCore.QRect(20, 90, 361, 16))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Dialog_ChuanHoa)
        self.label3.setGeometry(QtCore.QRect(20, 150, 361, 16))
        self.label3.setObjectName("label3")
        self.widget = QtWidgets.QWidget(Dialog_ChuanHoa)
        self.widget.setGeometry(QtCore.QRect(20, 169, 381, 25))
        self.widget.setObjectName("widget")
        self.gridLayout3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout3.setObjectName("gridLayout3")
        self.outputShapefile = QtWidgets.QLineEdit(self.widget)
        self.outputShapefile.setObjectName("outputShapefile")
        self.gridLayout3.addWidget(self.outputShapefile, 0, 0, 1, 1)
        self.btnOutput = QtWidgets.QPushButton(self.widget)
        self.btnOutput.setObjectName("btnOutput")
        self.gridLayout3.addWidget(self.btnOutput, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(Dialog_ChuanHoa)
        self.widget1.setGeometry(QtCore.QRect(20, 109, 381, 25))
        self.widget1.setObjectName("widget1")
        self.gridLayout2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setObjectName("gridLayout2")
        self.inputChurung = QtWidgets.QLineEdit(self.widget1)
        self.inputChurung.setObjectName("inputChurung")
        self.gridLayout2.addWidget(self.inputChurung, 0, 0, 1, 1)
        self.btnChurung = QtWidgets.QPushButton(self.widget1)
        self.btnChurung.setObjectName("btnChurung")
        self.gridLayout2.addWidget(self.btnChurung, 0, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(Dialog_ChuanHoa)
        self.widget2.setGeometry(QtCore.QRect(20, 50, 381, 25))
        self.widget2.setObjectName("widget2")
        self.gridLayout1 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout1.setObjectName("gridLayout1")
        self.inputShapefile = QtWidgets.QLineEdit(self.widget2)
        self.inputShapefile.setObjectName("inputShapefile")
        self.gridLayout1.addWidget(self.inputShapefile, 0, 0, 1, 1)
        self.btnInputShp = QtWidgets.QPushButton(self.widget2)
        self.btnInputShp.setObjectName("btnInputShp")
        self.gridLayout1.addWidget(self.btnInputShp, 0, 1, 1, 1)
        self.buttonBox.raise_()
        self.label1.raise_()
        self.label2.raise_()
        self.label3.raise_()
        self.btnOutput.raise_()
        self.outputShapefile.raise_()
        self.btnChurung.raise_()
        self.btnInputShp.raise_()
        self.inputChurung.raise_()
        self.inputShapefile.raise_()

        self.retranslateUi(Dialog_ChuanHoa)
        self.buttonBox.accepted.connect(Dialog_ChuanHoa.accept)
        self.buttonBox.rejected.connect(Dialog_ChuanHoa.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ChuanHoa)

    def retranslateUi(self, Dialog_ChuanHoa):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ChuanHoa.setWindowTitle(_translate("Dialog_ChuanHoa", "v5PFES - Chuẩn hóa bản đồ DBR"))
        self.label1.setText(_translate("Dialog_ChuanHoa", "Chọn lớp bản đồ diễn biến rừng (.shp)"))
        self.label2.setText(_translate("Dialog_ChuanHoa", "Chọn danh sách chủ rừng (.xlsx)"))
        self.label3.setText(_translate("Dialog_ChuanHoa", "Chọn thư mục lưu kết quả chuẩn hóa"))
        self.btnOutput.setText(_translate("Dialog_ChuanHoa", "..."))
        self.btnChurung.setText(_translate("Dialog_ChuanHoa", "..."))
        self.btnInputShp.setText(_translate("Dialog_ChuanHoa", "..."))

