# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_XuatBieu11_156.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_XuatBieu11_156(object):
    def setupUi(self, Dialog_XuatBieu11_156):
        Dialog_XuatBieu11_156.setObjectName("Dialog_XuatBieu11_156")
        Dialog_XuatBieu11_156.resize(564, 276)
        self.com_tinh = QtWidgets.QComboBox(Dialog_XuatBieu11_156)
        self.com_tinh.setGeometry(QtCore.QRect(20, 50, 161, 22))
        self.com_tinh.setObjectName("com_tinh")
        self.com_huyen = QtWidgets.QComboBox(Dialog_XuatBieu11_156)
        self.com_huyen.setGeometry(QtCore.QRect(200, 50, 161, 22))
        self.com_huyen.setObjectName("com_huyen")
        self.combo_xa = QtWidgets.QComboBox(Dialog_XuatBieu11_156)
        self.combo_xa.setGeometry(QtCore.QRect(380, 50, 161, 22))
        self.combo_xa.setObjectName("combo_xa")
        self.label = QtWidgets.QLabel(Dialog_XuatBieu11_156)
        self.label.setGeometry(QtCore.QRect(20, 31, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_XuatBieu11_156)
        self.label_2.setGeometry(QtCore.QRect(200, 31, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_XuatBieu11_156)
        self.label_3.setGeometry(QtCore.QRect(383, 32, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog_XuatBieu11_156)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 161, 16))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Dialog_XuatBieu11_156)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 521, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.output_path.setObjectName("output_path")
        self.horizontalLayout.addWidget(self.output_path)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_XuatBieu11_156)
        self.layoutWidget1.setGeometry(QtCore.QRect(377, 210, 161, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_OK = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_OK.setObjectName("btn_OK")
        self.horizontalLayout_2.addWidget(self.btn_OK)
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)

        self.retranslateUi(Dialog_XuatBieu11_156)
        QtCore.QMetaObject.connectSlotsByName(Dialog_XuatBieu11_156)

    def retranslateUi(self, Dialog_XuatBieu11_156):
        _translate = QtCore.QCoreApplication.translate
        Dialog_XuatBieu11_156.setWindowTitle(_translate("Dialog_XuatBieu11_156", "v5PFES - Xuất biểu số 11 Phụ lục VI NĐ-156"))
        self.label.setText(_translate("Dialog_XuatBieu11_156", "Chọn tỉnh"))
        self.label_2.setText(_translate("Dialog_XuatBieu11_156", "Chọn huyện"))
        self.label_3.setText(_translate("Dialog_XuatBieu11_156", "Chọn xã"))
        self.label_5.setText(_translate("Dialog_XuatBieu11_156", "Chọn thư mục lưu kết quả"))
        self.toolButton.setText(_translate("Dialog_XuatBieu11_156", "..."))
        self.btn_OK.setText(_translate("Dialog_XuatBieu11_156", "OK"))
        self.btn_cancel.setText(_translate("Dialog_XuatBieu11_156", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_XuatBieu11_156 = QtWidgets.QDialog()
    ui = Ui_Dialog_XuatBieu11_156()
    ui.setupUi(Dialog_XuatBieu11_156)
    Dialog_XuatBieu11_156.show()
    sys.exit(app.exec_())
