# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_CauHinh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_CauHinh(object):
    def setupUi(self, Dialog_CauHinh):
        Dialog_CauHinh.setObjectName("Dialog_CauHinh")
        Dialog_CauHinh.resize(329, 163)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_CauHinh)
        self.buttonBox.setGeometry(QtCore.QRect(-30, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_CauHinh)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label.setObjectName("label")
        self.cbBox_conf = QtWidgets.QComboBox(Dialog_CauHinh)
        self.cbBox_conf.setGeometry(QtCore.QRect(20, 50, 291, 22))
        self.cbBox_conf.setObjectName("cbBox_conf")

        self.retranslateUi(Dialog_CauHinh)
        self.buttonBox.accepted.connect(Dialog_CauHinh.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_CauHinh.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_CauHinh)

    def retranslateUi(self, Dialog_CauHinh):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CauHinh.setWindowTitle(_translate("Dialog_CauHinh", "v5PFES - Cấu hình làm việc"))
        self.label.setText(_translate("Dialog_CauHinh", "Chọn cấu hình làm việc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_CauHinh = QtWidgets.QDialog()
    ui = Ui_Dialog_CauHinh()
    ui.setupUi(Dialog_CauHinh)
    Dialog_CauHinh.show()
    sys.exit(app.exec_())
